{
    "CVE_data_meta": {
        "ASSIGNER": "secalert@redhat.com",
        "ID": "CVE-2010-4535",
        "STATE": "PUBLIC"
    },
    "affects": {
        "vendor": {
            "vendor_data": [
                {
                    "product": {
                        "product_data": [
                            {
                                "product_name": "n/a",
                                "version": {
                                    "version_data": [
                                        {
                                            "version_value": "n/a"
                                        }
                                    ]
                                }
                            }
                        ]
                    },
                    "vendor_name": "n/a"
                }
            ]
        }
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
        "description_data": [
            {
                "lang": "eng",
                "value": "The password reset functionality in django.contrib.auth in Django before 1.1.3, 1.2.x before 1.2.4, and 1.3.x before 1.3 beta 1 does not validate the length of a string representing a base36 timestamp, which allows remote attackers to cause a denial of service (resource consumption) via a URL that specifies a large base36 integer."
            }
        ]
    },
    "problemtype": {
        "problemtype_data": [
            {
                "description": [
                    {
                        "lang": "eng",
                        "value": "n/a"
                    }
                ]
            }
        ]
    },
    "references": {
        "reference_data": [
            {
                "name": "http://code.djangoproject.com/changeset/15032",
                "refsource": "CONFIRM",
                "url": "http://code.djangoproject.com/changeset/15032"
            },
            {
                "name": "[oss-security] 20101223 CVE Request -- Django 1.2.4, Django 1.1.3 and Django 1.3 beta 1 -- addressing two security flaws",
                "refsource": "MLIST",
                "url": "http://www.openwall.com/lists/oss-security/2010/12/23/4"
            },
            {
                "name": "USN-1040-1",
                "refsource": "UBUNTU",
                "url": "http://www.ubuntu.com/usn/USN-1040-1"
            },
            {
                "name": "45563",
                "refsource": "BID",
                "url": "http://www.securityfocus.com/bid/45563"
            },
            {
                "name": "[oss-security] 20110103 Re: CVE Request -- Django 1.2.4, Django 1.1.3 and Django 1.3 beta 1 -- addressing two security flaws",
                "refsource": "MLIST",
                "url": "http://www.openwall.com/lists/oss-security/2011/01/03/5"
            },
            {
                "name": "42913",
                "refsource": "SECUNIA",
                "url": "http://secunia.com/advisories/42913"
            },
            {
                "name": "ADV-2011-0048",
                "refsource": "VUPEN",
                "url": "http://www.vupen.com/english/advisories/2011/0048"
            },
            {
                "name": "ADV-2011-0098",
                "refsource": "VUPEN",
                "url": "http://www.vupen.com/english/advisories/2011/0098"
            },
            {
                "name": "http://www.djangoproject.com/weblog/2010/dec/22/security/",
                "refsource": "CONFIRM",
                "url": "http://www.djangoproject.com/weblog/2010/dec/22/security/"
            },
            {
                "name": "FEDORA-2011-0096",
                "refsource": "FEDORA",
                "url": "http://lists.fedoraproject.org/pipermail/package-announce/2011-January/053041.html"
            },
            {
                "name": "https://bugzilla.redhat.com/show_bug.cgi?id=665373",
                "refsource": "CONFIRM",
                "url": "https://bugzilla.redhat.com/show_bug.cgi?id=665373"
            },
            {
                "name": "42715",
                "refsource": "SECUNIA",
                "url": "http://secunia.com/advisories/42715"
            },
            {
                "name": "FEDORA-2011-0120",
                "refsource": "FEDORA",
                "url": "http://lists.fedoraproject.org/pipermail/package-announce/2011-January/053072.html"
            },
            {
                "name": "42827",
                "refsource": "SECUNIA",
                "url": "http://secunia.com/advisories/42827"
            }
        ]
    }
}