{
    "CVE_data_meta": {
        "ASSIGNER": "secalert@redhat.com",
        "ID": "CVE-2011-1950",
        "STATE": "PUBLIC"
    },
    "affects": {
        "vendor": {
            "vendor_data": [
                {
                    "product": {
                        "product_data": [
                            {
                                "product_name": "n/a",
                                "version": {
                                    "version_data": [
                                        {
                                            "version_value": "n/a"
                                        }
                                    ]
                                }
                            }
                        ]
                    },
                    "vendor_name": "n/a"
                }
            ]
        }
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
        "description_data": [
            {
                "lang": "eng",
                "value": "plone.app.users in Plone 4.0 and 4.1 allows remote authenticated users to modify the properties of arbitrary accounts via unspecified vectors, as exploited in the wild in June 2011."
            }
        ]
    },
    "problemtype": {
        "problemtype_data": [
            {
                "description": [
                    {
                        "lang": "eng",
                        "value": "n/a"
                    }
                ]
            }
        ]
    },
    "references": {
        "reference_data": [
            {
                "name": "44775",
                "refsource": "SECUNIA",
                "url": "http://secunia.com/advisories/44775"
            },
            {
                "name": "48005",
                "refsource": "BID",
                "url": "http://www.securityfocus.com/bid/48005"
            },
            {
                "name": "plone-data-security-bypass(67695)",
                "refsource": "XF",
                "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/67695"
            },
            {
                "name": "72729",
                "refsource": "OSVDB",
                "url": "http://osvdb.org/72729"
            },
            {
                "name": "8269",
                "refsource": "SREASON",
                "url": "http://securityreason.com/securityalert/8269"
            },
            {
                "name": "http://plone.org/products/plone/security/advisories/CVE-2011-1950",
                "refsource": "CONFIRM",
                "url": "http://plone.org/products/plone/security/advisories/CVE-2011-1950"
            },
            {
                "name": "20110526 [CVE-REQUEST] Plone XSS and permission errors",
                "refsource": "BUGTRAQ",
                "url": "http://www.securityfocus.com/archive/1/518155/100/0/threaded"
            }
        ]
    }
}